#!/bin/sh
# Installs the tools this course's labs use, at the versions of the LearnSome.tech lab sandbox, on x86-64
# Ubuntu: the dev container (Dockerfile) and CI (.github/workflows/check.yml) both run it, as root.
# `install-tools.sh ci` leaves out the Linux userland the labs call, which CI does not need.
# Generated by the LearnSome.tech platform (scripts/labs-repos); do not edit here.
set -eu
if [ "$(uname -m)" != x86_64 ]; then
  echo "install-tools.sh: x86-64 Linux only (Codespaces, GitHub Actions); elsewhere install the tools yourself" >&2
  exit 1
fi
mode=${1:-full}
here=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
fetch() { curl -fsSL --retry 3 "$1" -o "$2" && echo "$3  $2" | sha256sum -c - >/dev/null; }

export DEBIAN_FRONTEND=noninteractive
apt-get -o Acquire::Retries=5 -o Acquire::http::Timeout=30 -o Acquire::https::Timeout=30 update -q
apt-get install -y -q --no-install-recommends bash git unzip xz-utils ca-certificates curl
if [ "$mode" != ci ]; then
  apt-get install -y -q --no-install-recommends procps iproute2 util-linux findutils coreutils psmisc lsof strace less tree bc xxd binutils file acl gettext-base netcat-openbsd dnsutils iputils-ping traceroute net-tools openssh-client make patch bsdextrautils shellcheck
  # The sandbox's git is Ubuntu's; the base image puts a newer build first on PATH.
  if [ -x /usr/local/bin/git ] && [ -x /usr/bin/git ]; then ln -sf /usr/bin/git /usr/local/bin/git; fi
fi
rm -rf /var/lib/apt/lists/*
mkdir -p /opt/lab

# Python 3.14.7
fetch 'https://github.com/astral-sh/python-build-standalone/releases/download/20260924/cpython-3.14.7%2B20260924-x86_64-unknown-linux-gnu-install_only_stripped.tar.gz' "$tmp/python.tgz" bd0d0568ccded07bbf1c87727230dc5dd0187e706a87da23c4de78388a229b78
mkdir -p /opt/python && tar -xzf "$tmp/python.tgz" -C /opt/python --strip-components=1
ln -sf /opt/python/bin/python3.14 /usr/local/bin/python3
ln -sf /opt/python/bin/python3.14 /usr/local/bin/python

# kubeconform 0.8.0 and the Kubernetes schemas the sandbox validates against
fetch 'https://github.com/yannh/kubeconform/releases/download/v0.8.0/kubeconform-linux-amd64.tar.gz' "$tmp/kubeconform.tgz" 9bc2bffbf71f261128533edaf912153948b7ff238f9a531ae6d34466ec287883
tar -xzf "$tmp/kubeconform.tgz" -C /usr/local/bin kubeconform && chmod 0755 /usr/local/bin/kubeconform
mkdir -p /opt/lab/k8s-schemas
while read -r sum name; do fetch "https://raw.githubusercontent.com/yannh/kubernetes-json-schema/8df8a883b68a24a104b4a9e43c1288090ae60b3b/master-standalone-strict/$name" "/opt/lab/k8s-schemas/$name" "$sum"; done < "$here/k8s-schemas.sha256"

# ansible-core and yamllint in their own environment (hash-pinned, as in the sandbox)
/opt/python/bin/python3.14 -m venv /opt/pytools
/opt/pytools/bin/pip install -q --no-cache-dir --disable-pip-version-check --require-hashes --only-binary=:all: -r "$here/requirements.txt"
install -m 0755 "$here/ansible-tool" /opt/lab/ansible-tool
for t in ansible ansible-playbook ansible-inventory ansible-config ansible-doc ansible-galaxy ansible-vault ansible-console ansible-pull; do
  ln -sf /opt/lab/ansible-tool "/usr/local/bin/$t"
done
ln -sf /opt/pytools/bin/yamllint /usr/local/bin/yamllint

# The toolchains also under /opt/lab/bin, the sandbox's own PATH entry
mkdir -p /opt/lab/bin
ln -sf /opt/python/bin/python3.14 /opt/lab/bin/python3
ln -sf /opt/python/bin/python3.14 /opt/lab/bin/python
